//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroNotas
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstudianteGrupo
    {
        public int IdEstGrup { get; set; }
        public int IdEstudiante { get; set; }
        public int IdGrupo { get; set; }
        public int IdEstadoEst { get; set; }
        public Nullable<int> Activo { get; set; }
    
        public virtual EstadoEstudiante EstadoEstudiante { get; set; }
        public virtual Estudiante Estudiante { get; set; }
        public virtual Grupo Grupo { get; set; }
    }
}
