//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroNotas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grupo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Grupo()
        {
            this.EstudianteGrupo = new HashSet<EstudianteGrupo>();
            this.Rubrica = new HashSet<Rubrica>();
        }
    
        public int IdGrupo { get; set; }
        public System.DateTime Hora { get; set; }
        public string Aula { get; set; }
        public int EstadoGrupo { get; set; }
        public int IdCurso { get; set; }
        public int IdProfesor { get; set; }
        public int IdPeriodo { get; set; }
        public Nullable<int> Activo { get; set; }
    
        public virtual Curso Curso { get; set; }
        public virtual EstadoGrupo EstadoGrupo1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EstudianteGrupo> EstudianteGrupo { get; set; }
        public virtual PeriodoLectivo PeriodoLectivo { get; set; }
        public virtual Profesor Profesor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rubrica> Rubrica { get; set; }
    }
}
